name: Publish Release

env:
  BuildDir: ./bld
  ScriptDir: ./scripts
  SrcDir: ./src
  Prerelease: false

on:
  push:
    tags:
    - 'v*'

defaults:
  run:
    shell: pwsh

jobs:
  pub_create_github_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create Release Notes
      run: ${{ env.ScriptDir }}/publish-releasenotes.ps1

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.Product }} ${{ github.ref }}
        body_path: ${{ env.BuildDir }}/ReleaseNotes.md
        draft: false
        prerelease: ${{ env.Prerelease }}

  pub_build_and_upload:
    name: Publish Build
    runs-on: ubuntu-latest
    needs: pub_create_github_release
    steps:

    - name: Get Version
      run: |
        . ${{ env.ScriptDir }}/utils.ps1
        $env:HawSpellVersion = Get-Version
        Write-Host HawSpell v$env:HawSpellVersion

    - name: Build Hunspell dictionary
      run: ${{ env.ScriptDir }}/build-hunspell.ps1

    - name: Upload Hunspell Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.pub_create_github_release.outputs.upload_url }}
        asset_path: ${{ env.BuildDir }}/HawSpell_${{ $env:HawSpellVersion }}.zip
        asset_name: HawSpell_${{ $env:HawSpellVersion }}.zip
        asset_content_type: application/zip

    - name: Build Firefox extension
      run: ${{ env.ScriptDir }}/build-firefox.ps1

    - name: Upload Firefox Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.pub_create_github_release.outputs.upload_url }}
        asset_path: ${{ env.BuildDir }}/HawSpell_${{ $env:HawSpellVersion }}.xpi
        asset_name: HawSpell_${{ $env:HawSpellVersion }}.xpi
        asset_content_type: application/x-xpinstall

    - name: Build OpenOffice extension
      run: ${{ env.ScriptDir }}/build-openoffice.ps1

    - name: Upload OpenOffice Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.pub_create_github_release.outputs.upload_url }}
        asset_path: ${{ env.BuildDir }}/HawSpell_${{ $env:HawSpellVersion }}.oxt
        asset_name: HawSpell_${{ $env:HawSpellVersion }}.oxt
        asset_content_type: application/vnd.openofficeorg.extension